name = "ash/mastermind-aiken"
version = "0.0.1"
license = "Apache-2.0"
description = "Aiken contracts for project 'ash/mastermind-aiken'"

[repository]
user = "ash"
project = "mastermind-aiken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.7.0"
source = "github"

[[dependencies]]
name = "modulo-p/ak-381"
version = "v0.1"
source = "github"
